### ISSUE TITLE
Is this fork dead?

### ISSUE THREAD

**Issue by nagyt234** [appfolio/ae_declarative_authorization#30]
Is this fork of declarative_authorization dead? Is any other one for rails 6 and 7?

**Comment by dvicory** [comment]
It is not dead - we are still using this internally. There are appraisals for Rails 6 and 7, and the test suites are running there. Let us know if you encounter any issues!

**Comment by nagyt234** [comment]
Thx. Our system was migrated from rails 5 to rails 6. I did not encounter any issues with rails 6.0.6.1, 6.1.7.3. We try to migrate our system to rails 7 in the next weeks.
